DROP TABLE IF EXISTS NABAVLJA
DROP TABLE IF EXISTS AUTOMOBIL
DROP TABLE IF EXISTS VRSTAAUTOMOBILA
DROP TABLE IF EXISTS AUTOBUS
DROP TABLE IF EXISTS SEDOLAZI
DROP TABLE IF EXISTS REZERVISE
DROP TABLE IF EXISTS PREVOZNOSREDSTVO
DROP TABLE IF EXISTS SMESTAJ
DROP TABLE IF EXISTS TIPSMESTAJA
DROP TABLE IF EXISTS OBUHVATA
DROP TABLE IF EXISTS DESTINACIJA
DROP TABLE IF EXISTS KLIJENT
DROP TABLE IF EXISTS NUDI
DROP TABLE IF EXISTS PUTOVANJE
DROP TABLE IF EXISTS VODIC
DROP TABLE IF EXISTS AGENCIJA


CREATE TABLE AGENCIJA(
	IdAg integer IDENTITY(1,1) NOT NULL,
	NazAg varchar(30) NOT NULL,
	AdrAg varchar(30) NOT NULL,
	CONSTRAINT AG_PK PRIMARY KEY (IdAg)
);

CREATE TABLE VODIC(
	IdVod integer IDENTITY(1,1) NOT NULL,
	JmbgVod VARCHAR(13) NOT NULL,
	ImeVod varchar(30) NOT NULL,
	PrzVod varchar(30) NOT NULL,
	BrVod varchar(30) NOT NULL,
	idAg integer,
	CONSTRAINT V_UN UNIQUE (JmbgVod),
	CONSTRAINT VODIC_PK PRIMARY KEY (IdVod),
	CONSTRAINT VODIC_FK FOREIGN KEY (IdAg) REFERENCES AGENCIJA(IdAg)
);

CREATE TABLE PUTOVANJE(
	IdPuta integer IDENTITY(1,1) NOT NULL,
	NazPuta varchar(30) NOT NULL,
	CenaPuta integer NOT NULL,
	DatumPol DATETIME NOT NULL,
	DatumPov DATETIME NOT NULL,
	CONSTRAINT PUT_PK PRIMARY KEY (IdPuta)

);

CREATE TABLE NUDI(
	IdNudi integer IDENTITY(1,1) NOT NULL,
	IdAg integer NOT NULL,
	IdPuta integer NOT NULL,
	CONSTRAINT NUDI_FK_PUT FOREIGN KEY (IdPuta) REFERENCES PUTOVANJE(IdPuta),
	CONSTRAINT NUDI_FK_AG FOREIGN KEY (IdAg) REFERENCES AGENCIJA(IdAg),
	CONSTRAINT NUDI_PK PRIMARY KEY (IdNudi)
);

CREATE TABLE KLIJENT(
	IdK integer IDENTITY(1,1) NOT NULL,
	JmbgK VARCHAR(13) NOT NULL,
	ImeK char(30) NOT NULL,
	PrzK char(30) NOT NULL,
	BrK varchar(30) NOT NULL
	CONSTRAINT K_PK PRIMARY KEY (IdK),
	CONSTRAINT K_UN UNIQUE (JmbgK)
);


CREATE TABLE DESTINACIJA(
	IdDest integer IDENTITY(1,1) NOT NULL,
	NazDest varchar(30) NOT NULL,
	CONSTRAINT DEST_PK PRIMARY KEY (IdDest)
);

CREATE TABLE OBUHVATA(
	IdObuhvata integer IDENTITY(1,1) NOT NULL,
	IdPuta integer NOT NULL,
	IdDest integer NOT NULL,
	CONSTRAINT OBUHVATA_PK PRIMARY KEY (IdObuhvata),
	CONSTRAINT OBUHVATA_FK_PUT FOREIGN KEY (IdPuta) REFERENCES PUTOVANJE(IdPuta),
	CONSTRAINT OBUHVATA_FK_DEST FOREIGN KEY (IdDest) REFERENCES DESTINACIJA(IdDest)

);

CREATE TABLE TIPSMESTAJA(
	IdTipa integer IDENTITY(1,1) NOT NULL,
	NazTipa varchar(30) NOT NULL,
	CONSTRAINT TIPSMESTAJA_PK PRIMARY KEY (IdTipa)
);

CREATE TABLE SMESTAJ(
	IdDest integer NOT NULL,
	IdSm integer IDENTITY(1,1) NOT NULL,
	NazSm varchar(30) NOT NULL,
	IdTipa integer NOT NULL,
	CONSTRAINT SMESTAJ_PK PRIMARY KEY (IdSm),
	CONSTRAINT SMESTAJ_FK_DEST FOREIGN KEY (IdDest) REFERENCES DESTINACIJA(IdDest),
	CONSTRAINT SMESTAJ_FK_TIP FOREIGN KEY (IdTipa) REFERENCES TIPSMESTAJA(IdTipa)
);

CREATE TABLE PREVOZNOSREDSTVO(
	IdPrzs integer IDENTITY(1,1) NOT NULL,
	KategorijaPrzs varchar(30) NOT NULL,
	CONSTRAINT PREVOZNOSREDSTVO_PK PRIMARY KEY (IdPrzs)
);

CREATE TABLE REZERVISE(
	IdK integer NOT NULL,
	IdPuta integer NOT NULL,
	IdPrzs integer NOT NULL,
	IdAg integer NOT NULL,
	CONSTRAINT REZERVISE_FK_KLIJENT FOREIGN KEY (IdK) REFERENCES KLIJENT(IdK),
	CONSTRAINT REZERVISE_FK_PUT FOREIGN KEY (IdPuta) REFERENCES PUTOVANJE(IdPuta),
	CONSTRAINT REZERVISE_FK_PRZS FOREIGN KEY (IdPrzs) REFERENCES PREVOZNOSREDSTVO(IdPrzs),
	CONSTRAINT REZERVISE_FK_AG FOREIGN KEY (IdAg) REFERENCES AGENCIJA(IdAg),
	CONSTRAINT REZERVISE_PK PRIMARY KEY (IdK, IdAg, IdPuta)
);

CREATE TABLE SEDOLAZI(
	IdSeDolazi integer IDENTITY(1,1) NOT NULL,
	IdDest integer NOT NULL,
	IdPrzs integer NOT NULL,
	CONSTRAINT SEDOLAZI_PK PRIMARY KEY (IdSeDolazi),
	CONSTRAINT SEDOLAZI_FK_DEST FOREIGN KEY (IdDest) REFERENCES DESTINACIJA(IdDest),
	CONSTRAINT SEDOLAZI_FK_PRZS FOREIGN KEY (IdPrzs) REFERENCES PREVOZNOSREDSTVO(IdPrzs)
);

CREATE TABLE AUTOBUS(
	BrMesta integer NOT NULL,
	RegBrBus varchar(10) NOT NULL,
	IdPrzs integer NOT NULL,
	CONSTRAINT AUTOBUS_UN UNIQUE (RegBrBus),
	CONSTRAINT AUTOBUS_FK FOREIGN KEY (IdPrzs) REFERENCES PREVOZNOSREDSTVO(IdPrzs),
	CONSTRAINT PREVOZNOSREDSTVO_PK_AUTOBUS PRIMARY KEY (IdPrzs)
);

CREATE TABLE VRSTAAUTOMOBILA(
	IdVrste integer IDENTITY(1,1) NOT NULL,
	NazVrste varchar(20) NOT NULL,
	CONSTRAINT VRSTAAUTOMOBILA_PK PRIMARY KEY (IdVrste)
);

CREATE TABLE AUTOMOBIL(
	RegBrAuto varchar(10) NOT NULL,
	IdVrste integer NOT NULL,
	IdPrzs integer NOT NULL,
	CONSTRAINT AUTOMOBIL_UN UNIQUE (RegBrAuto),
	CONSTRAINT AUTOMOBIL_FK_VRSTA FOREIGN KEY (IdVrste) REFERENCES VRSTAAUTOMOBILA(IdVrste),
	CONSTRAINT AUTOMOBIL_FK_PRZS FOREIGN KEY (IdPrzs) REFERENCES PREVOZNOSREDSTVO(IdPrzs),
	CONSTRAINT AUTOMOBIL_PK PRIMARY KEY (IdPrzs)
);

CREATE TABLE NABAVLJA(
	IdNabavlja integer IDENTITY(1,1) NOT NULL,
	IdAg integer NOT NULL,
	IdPrzs integer NOT NULL,
	CONSTRAINT NABAVLJA_FK_AG FOREIGN KEY (IdAg) REFERENCES AGENCIJA(IdAg),
	CONSTRAINT NABAVLJA_FK_PRZS FOREIGN KEY (IdPrzs) REFERENCES PREVOZNOSREDSTVO(IdPrzs),
	CONSTRAINT NABAVLJA_PK PRIMARY KEY (IdNabavlja)
);